language: node_js
os:
  - linux
  - windows
node_js:
- 10.15.1
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install jq; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install zip; fi
  - npm install
  - npm install mocha@5.2.0 -g
script:
  - mocha test --recursive -u tdd --exit
before_deploy:
  - "./release.sh 6.6.0"
  - "./release.sh 6.6.1"
  - "./release.sh 7.0.0-beta1"
deploy:
  provider: releases
  api_key:
    secure: C4Wc30K1bdWeODeSTaoGUqd7OgsSoSJL5iC0dyfHNsLOvp+NzY/Ws7YL/cXeCF7scNFTfCDnjWqC5231Y1490IkMun05QYOMDoum52arTYVhGrfJwXeNOLG4O0KISXsCzhD55vBAslI7Y6Nb6idK4hhdfk+15Apzx7bsY5llxGgSklf7lRetZh3jPeL+IcIHz5XxbiQseDDNyP6DuxLjfZLNvWTyi2rlaLkg6koIHrf+Gy+aV9UM+prXwGSwby8Mnpsvvi8k2RCzRZwG6+LzifayOYstXI2GG/fAlNfSLdEwKhQkGi+bqCZaXuUQpb9oKN7SY4iGiZfJ4Fh9J6Uzlk/ruJvovgguOLi7dkbNUvvNCvEyGJkQ1IouA2a31KgHyr8tSESlN2pzLKtjPmAIQe3y4LcqDFFtoK8zlr7FtAfwTf4xjMkQ4rGTGS4us4ygpDkT08arutc3HUu0vXe3gJQUlypXRiLQIdt/7uUC7gzy/RGhaDzZbuhV0XQFoxlN2PwSm0bz74pJm/LQM7YlSo4pq+oUcA6rbCtThgV4zHo2rxlC/c7m+BFKxcBRpG/QAxpQ6CxAKdo+wceoeawI7mGVt7PV+nk1ovS/EpJOlWi8H0EMhTrFKOP/g6HCivr+PvK45+7vtNbJLpWrN2cHXQK+tsGVbuOM6q4TwLQODbk=
  file_glob: true
  file: "build/dist/*"
  skip_cleanup: true
  on:
    tags: true
